title: Install QuickCreator Skill Builder
description: Install the QuickCreator Skill Builder into your AI assistant.
remote_theme: just-the-docs/just-the-docs@v0.10.1
url: "https://skills.quickcreator.io"
baseurl: ""

permalink: pretty

aux_links:
  "GitHub":
    - "https://github.com/kycloudtech/quickcreator-skills"

aux_links_new_tab: true

color_scheme: light

footer_content: "Copyright &copy; 2024-2026 <a href=\"https://www.quickcreator.io\">QuickCreator</a>."

search_enabled: false

plugins:
  - jekyll-seo-tag
